import type { Metadata } from "next";
import { Inter } from "next/font/google";
<<<<<<< HEAD
import "./styles/globals.scss";
=======
import "./styles/globals.css";
import { Providers } from "./providers";
>>>>>>> 5ec007dbc3ce1614bb43c6fcaa0ed8986518b02e

const geistInter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistInter.variable} `}>
      <Providers>
        {children}
      </Providers>
      </body>
    </html>
  );
}
