import { MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import Toast from "./components/Toast/Toast";
const geistInter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistInter.variable} `}>
        <Toast
          Position="bottom-right"
          Variant="success"
          Title="Success to update"
          Description=" ReferenceError: Toast is not defined"
        ></Toast>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
