import { MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import { AuthProvider} from "@/app/Context/AuthContext/AuthContext";

const geistInter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistInter.variable} `}>
      <AuthProvider>
        <MantineProvider>
          {children}
        </MantineProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
